///
////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/// @file
/// @brief Increments build number, date, and time each time software is built
///
/// This file was automatically generated using Stratovan Encircle(TM) EncircleIncrementVersion.exe
/// Do not edit this file directly. This file is updated automatically prior to each build.
///
/// Copyright (C) 2023 by Stratovan Corporation. All rights reserved.
/// See the associated license file for more information.
////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///

#ifndef _STRATOVAN_DICOS_VERSION_H_
#define _STRATOVAN_DICOS_VERSION_H_

namespace SDICOS
{

int	GetBuildYear();		//!< The year when this software was last built
int	GetBuildMonth();	//!< The month when this software was last built
int	GetBuildDay();		//!< The day when this software was last built
int	GetBuildTime();		//!< The time when this software was last built

const char*	GetBuildVersion();		//!< The software version string i.e., "2015.03.18.0102" corresponds to year 2015, month of March, day 18, at a time of 1:02pm
const char*	GetBuildOperatingSystem();	//!< The operating system one of {"WIN", "LIN", "OSX"}
const char*	GetBuildType();			//!< The application build type one of {"debug", "release"}
int			GetBuildBit();			//!< The application build bit type one of {32, 64}

} // namespace SDICOS

#endif  // _STRATOVAN_DICOS_VERSION_H_

