name: Bug Report
description: Problems with pyDICOS
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a pyDICOS Bug Report!

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search the past [issues](https://github.com/Auxilia-tech/pyDICOS/issues) to see if a similar bug report already exists.
      options:
        - label: >
            I have searched the [issues](https://github.com/Auxilia-tech/pyDICOS/issues) and found no similar bug report.
          required: true

  - type: textarea
    attributes:
      label: Bug
      description: Provide console output with error messages and/or screenshots of the bug.
      placeholder: |
        Include as much information as possible (screenshots, logs, tracebacks etc.) to receive the most helpful response.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Minimal Reproducible Example
      description: >
        When asking a question, people will be better able to provide help if you provide code that they can easily understand and use to **reproduce** the problem.
      placeholder: |
        ```
        # Code to reproduce your issue here
        ```
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share?

  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: >
        (Optional) We encourage you to submit a [Pull Request](https://github.com/Auxilia-tech/pyDICOS/pulls) (PR) to help improve pyDICOS for everyone, especially if you have a good understanding of how to implement a fix or feature.
      options:
        - label: Yes I'd like to help by submitting a PR!