name: Question
description: Ask a question
labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for asking a question!

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search the [issues](https://github.com/Auxilia-tech/pyDICOS/issues) and [discussions](https://github.com/Auxilia-tech/pyDICOS/discussions) to see if a similar question already exists.
      options:
        - label: >
            I have searched the [issues](https://github.com/Auxilia-tech/pyDICOS/issues) and [discussions](https://github.com/Auxilia-tech/pyDICOS/discussions) and found no similar questions.
          required: true

  - type: textarea
    attributes:
      label: Question
      description: What is your question?
      placeholder: |
        Include as much information as possible (screenshots, logs, tracebacks etc.) to receive the most helpful response.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share?